<font size="10">Exercise 1</font>

In [15]:
import pandas as pd


data = {
    "Title": [
        "Harry Potter and the Philosopher's Stone",
        "The Hobbit",
        "1984",
        "Pride and Prejudice",
        "The Great Gatsby",
        "To Kill a Mockingbird"
    ],
    "Author": [
        "J.K. Rowling",
        "J.R.R. Tolkien",
        "George Orwell",
        "Jane Austen",
        "F. Scott Fitzgerald",
        "Harper Lee"
    ],
    "Year of publication": [
        1997, 1937, 1949, 1813, 2025, 2016
    ],
    "Price": [
        15.99, 12.50, 10.99, 9.50, 11.25, 13.75
    ]
}

df = pd.DataFrame(data)

df

,Title,Author,Year of publication,Price
0,Harry Potter and the Philosopher's Stone,J.K. Rowling,1997,15.99
1,The Hobbit,J.R.R. Tolkien,1937,12.50
2,1984,George Orwell,1949,10.99
3,Pride and Prejudice,Jane Austen,1813,9.50
4,The Great Gatsby,F. Scott Fitzgerald,2025,11.25
5,To Kill a Mockingbird,Harper Lee,2016,13.75

In [24]:
average_price = df['Price'].mean()
average_price

np.float64(12.33)

In [18]:
BooksAfter2015 = df[df['Year of publication'] > 2015]
BooksAfter2015

                   Title               Author  Year of publication  Price
4       The Great Gatsby  F. Scott Fitzgerald                 2025  11.25
5  To Kill a Mockingbird           Harper Lee                 2016  13.75

In [19]:
sortedDf = df.sort_values(by='Price')
sortedDf

,Title,Author,Year of publication,Price
3,Pride and Prejudice,Jane Austen,1813,9.50
2,1984,George Orwell,1949,10.99
4,The Great Gatsby,F. Scott Fitzgerald,2025,11.25
1,The Hobbit,J.R.R. Tolkien,1937,12.50
5,To Kill a Mockingbird,Harper Lee,2016,13.75
0,Harry Potter and the Philosopher's Stone,J.K. Rowling,1997,15.99

<font size="10">Exercise 2</font>

In [21]:
df1 = pd.read_csv("Orders.csv")
df1

    Order number           Customer       Date   Price
0           1001         John Smith   1/1/2026   25.99
1           1002       Emma Johnson   1/2/2026   43.34
2           1003      Michael Brown   1/3/2026   60.69
3           1004       Olivia Davis   1/4/2026   78.04
4           1005       James Wilson   1/5/2026   95.39
5           1006      Sophia Miller   1/6/2026  112.74
6           1007     William Taylor   1/7/2026  130.09
7           1008  Isabella Anderson   1/8/2026  147.44
8           1009    Benjamin Thomas   1/9/2026  164.79
9           1010        Mia Jackson  1/10/2026  182.14
10          1011         John Smith  1/11/2026  199.49
11          1012       Emma Johnson  1/12/2026  216.84
12          1013      Michael Brown  1/13/2026  234.19
13          1014       Olivia Davis  1/14/2026  251.54
14          1015       James Wilson  1/15/2026   18.89
15          1016      Sophia Miller  1/16/2026   36.24
16          1017     William Taylor  1/17/2026   53.59
17          1018  Isabella Anderson  1/18/2026   70.94
18          1019    Benjamin Thomas  1/19/2026   88.29
19          1020        Mia Jackson  1/20/2026  105.64
20          1021         John Smith  1/21/2026  122.99
21          1022       Emma Johnson  1/22/2026  140.34
22          1023      Michael Brown  1/23/2026  157.69
23          1024       Olivia Davis  1/24/2026  175.04
24          1025       James Wilson  1/25/2026  192.39
25          1026      Sophia Miller  1/26/2026  209.74
26          1027     William Taylor  1/27/2026  227.09
27          1028  Isabella Anderson  1/28/2026  244.44
28          1029    Benjamin Thomas  1/29/2026  261.79
29          1030        Mia Jackson  1/30/2026   29.14
30          1031         John Smith  1/31/2026   46.49
31          1032       Emma Johnson   2/1/2026   63.84
32          1033      Michael Brown   2/2/2026   81.19
33          1034       Olivia Davis   2/3/2026   98.54
34          1035       James Wilson   2/4/2026  115.89
35          1036      Sophia Miller   2/5/2026  133.24
36          1037     William Taylor   2/6/2026  150.59
37          1038  Isabella Anderson   2/7/2026  167.94
38          1039    Benjamin Thomas   2/8/2026  185.29
39          1040        Mia Jackson   2/9/2026  202.64
40          1041         John Smith  2/10/2026  219.99
41          1042       Emma Johnson  2/11/2026  237.34
42          1043      Michael Brown  2/12/2026  254.69
43          1044       Olivia Davis  2/13/2026   22.04
44          1045       James Wilson  2/14/2026   39.39
45          1046      Sophia Miller  2/15/2026   56.74
46          1047     William Taylor  2/16/2026   74.09
47          1048  Isabella Anderson  2/17/2026   91.44
48          1049    Benjamin Thomas  2/18/2026  108.79
49          1050        Mia Jackson  2/19/2026  126.14

In [22]:
df1.head(10)

   Order number           Customer       Date   Price
0          1001         John Smith   1/1/2026   25.99
1          1002       Emma Johnson   1/2/2026   43.34
2          1003      Michael Brown   1/3/2026   60.69
3          1004       Olivia Davis   1/4/2026   78.04
4          1005       James Wilson   1/5/2026   95.39
5          1006      Sophia Miller   1/6/2026  112.74
6          1007     William Taylor   1/7/2026  130.09
7          1008  Isabella Anderson   1/8/2026  147.44
8          1009    Benjamin Thomas   1/9/2026  164.79
9          1010        Mia Jackson  1/10/2026  182.14

In [27]:
counts = df1['Customer'].value_counts()
repeated_names = counts[counts > 1]
repeated_names

Customer
John Smith           5
Emma Johnson         5
Michael Brown        5
Olivia Davis         5
James Wilson         5
Sophia Miller        5
William Taylor       5
Isabella Anderson    5
Benjamin Thomas      5
Mia Jackson          5
Name: count, dtype: int64

In [25]:
max_price = df1['Price'].max()

min_price = df1['Price'].min()

max_price, min_price

(np.float64(261.79), np.float64(18.89))

In [31]:
total_price = df1['Price'].sum()

total_price

np.float64(6553.250000000001)